name: CI

on:
  push:
    branches:
      - master
env:
  REPOSITORY_PATH: https://${{secrets.ACCESS_TOKEN}}@github.com/
  # GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@gmail.com"
      - name: pull-code
        uses: actions/checkout@v2
      - name: install-node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install-dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: build
        run: |
          npm run deploy
          cp -rp dist/ng-cli-plugin/ ../dist
          git branch gh-pages
          git checkout gh-pages
          rm -rf *
          cp -rp ../dist/* .
          cp ./index.html 404.html
      - name: tag
        run: |
          git status
          git add -A
          git commit -m '页面构建'
          git push --force "${REPOSITORY_PATH}${GITHUB_REPOSITORY}.git" gh-pages
          # git pull
